import type { Metadata } from "next";
import "../styles/base.scss";
import styles from "./layout.module.scss";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={styles.body}>
        <Header />
        <Sidebar />
        {children}
      </body>
    </html>
  );
}
